# Generated by Django 6.0.5 on 2026-05-14 23:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardChamados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150)),
                ('status_atual', models.CharField(max_length=60)),
                ('tempo_resolucao', models.CharField(blank=True, max_length=100, null=True)),
                ('categoria', models.CharField(blank=True, max_length=100, null=True)),
                ('data', models.DateField(auto_now_add=True)),
            ],
            options={
                'db_table': 'dashboard_chamados',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_firebase', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('cargo', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'usuarios',
            },
        ),
        migrations.CreateModel(
            name='Chamado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150)),
                ('descricao', models.TextField(max_length=255)),
                ('status', models.CharField(choices=[('Aberto', 'Aberto'), ('Em andamento', 'Em andamento'), ('Fechado', 'Fechado')], default='Aberto', max_length=60)),
                ('data_abertura', models.DateTimeField(auto_now_add=True)),
                ('id_usuario', models.ForeignKey(db_column='id_usuario', on_delete=django.db.models.deletion.CASCADE, to='core.usuario')),
            ],
            options={
                'db_table': 'chamados',
            },
        ),
    ]
